name: Test

on:
  pull_request:
  push:
  #schedule:
  #  - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - 'pypy-3.8'
          - 'pypy-3.9'
        toxenv: [py]
        include:
          - python-version: '3.8'
            toxenv: lint
            os: ubuntu-latest
          - python-version: '3.8'
            toxenv: typing
            os: ubuntu-latest
        exclude:
          # The code doesn't seem to work under PyPy on Windows, and I'm not
          # interested in figuring out why.
          - python-version: 'pypy-3.8'
            toxenv: py
            os: windows-latest
          - python-version: 'pypy-3.9'
            toxenv: py
            os: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager tox
          python -m pip install --upgrade datalad-installer

      - name: Install git-annex (Ubuntu)
        if: matrix.toxenv == 'py' && startsWith(matrix.os, 'ubuntu')
        run: datalad-installer -l DEBUG --sudo ok neurodebian git-annex -m neurodebian

      - name: Install git-annex (macOS)
        if: matrix.toxenv == 'py' && startsWith(matrix.os, 'macos')
        run: datalad-installer -l DEBUG --sudo ok git-annex -m brew

      - name: Install git-annex (Windows)
        if: matrix.toxenv == 'py' && startsWith(matrix.os, 'windows')
        run: datalad-installer -l DEBUG --sudo ok git-annex -m datalad/git-annex:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests with coverage
        if: matrix.toxenv == 'py'
        run: tox -e py -- --cov-report=xml

      - name: Run generic tests
        if: matrix.toxenv != 'py'
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: matrix.toxenv == 'py'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

# vim:set et sts=2:
